global using FluentResults;
global using FluentValidation;
global using iot.Application.Common.Constants;
global using iot.Application.Common.Models;
global using iot.Application.Repositories.UnitOfWorks.Identity;
global using iot.Domain.Entities.Identity;
global using iot.Domain.ValueObjects;
global using MediatR;
global using Microsoft.EntityFrameworkCore;